### ISSUE TITLE
-bash: compopt: command not found

### ISSUE THREAD

**Issue by matthewharwood** [alrra/dotfiles#8]
First time user. (bit of a noob with These kind of things)
Getting an error saying
-bash: compopt: command not found 
Recreate
`$ cd`
`cd Down` then tab complete
`$ cd Down-bash: compopt: command not found
loads`

**Comment by matthewharwood** [comment]
I think I need to update Bash but I have no idea on how to go about that ( I seem to remember it failing in the building)

**Comment by alrra** [comment]
> commented 6 days ago 

Sorry for the delayed answer! I somehow missed the email notification. :(

> (bit of a noob with These kind of things)

Don't worry! 
  
--

> -bash: compopt: command not found 

The problem seems to be because of `bash-completion2` (see: https://github.com/Homebrew/homebrew/issues/39014). 

>  need to update Bash

Yes, you need to update to `Bash 4.x` in order for `bash-completion2` to work.

(Note: Recent versions of Ubuntu come with Bash `4.x` installed by default, and for OS X, the dotfiles should take care of [installing](https://github.com/alrra/dotfiles/blob/cd0131607fa640e1a233d5660b0d51256c269559/os/os_x/install_applications.sh#L9) Bash 4.x and [making it the default](https://github.com/alrra/dotfiles/blob/fc33e5037700acde80d0b74f3ecbdee0fdd913dd/os/os_x/change_default_bash_version.sh)).

> I think I need to update Bash but I have no idea on how to go about that

What OS are you using? 

> I seem to remember it failing in the building)

Are you talking about the dotfiles setup or something else?

**Comment by alrra** [comment]
> The problem seems to be because of `bash-completion2`
>
> Yes, you need to update to Bash 4.x in order for bash-completion2 to work.

@matthewharwood I checked, and indeed, the problem is because of you don't have Bash `4.x`. 

Try to run the setup process again, or manually try to fix your setup to use Bash `4.x`. If you do nor succeed, you can just go with `bash-completion` which is compatible with earlier version of Bash ([see differences](https://github.com/alrra/dotfiles/commit/7e9aefaf18fa4a6027603f65d91a3db3672581d4)).

**Comment by matthewharwood** [comment]
@alrra sorry man I was out of town on vacation for the last week.  
![screen shot 2015-06-09 at 13 37 51](https://cloud.githubusercontent.com/assets/1505266/8056288/92b61448-0e5b-11e5-84a3-614d98f25592.png)
after re install.  Bash-completion2 works but it jsut throws that annoying error everytime.  

$ bash --version
GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin14.1.0)

**Comment by alrra** [comment]
>  on vacation for the last week

@matthewharwood Hope you had a great time! :palm_tree: 

> but Bash-completion2 does work.

I'm glad that now works for you.

> So I get an error everytime still
> Any ideas?

Can you tell me what the following prints out:

```bash
chsh -s "$(brew --prefix)/bin/bash"; echo $?
```

**Comment by matthewharwood** [comment]
Changing shell for matty.
Password for matty: 
chsh: /usr/local/bin/bash: non-standard shell
1

**Comment by alrra** [comment]
> Changing shell for matty.
Password for matty:
chsh: /usr/local/bin/bash: non-standard shell
1

@matthewharwood Should be fixed by https://github.com/alrra/dotfiles/commit/efa2d8306158ecb7d3c7cde1641e71053152e6e5 . Sorry for the inconvenience, and thanks for opening this issue!

**Comment by matthewharwood** [comment]
@alrra I still getting the same error after re-running your ```bash -c "$(curl -LsS https://raw.github.com/alrra/dotfiles/master/dotfiles)"```  However, I've used your script on a fresh computer I got from work and it worked perfectly. As before Using the last version of Bash always comes up red.  So, I'm curious, if the act updating the my env. pre  efa2d83 vs. creating fresh just wont work as intended.  Might you have any ideas on how to fix the `-bash: compopt: command not found`


`chsh -s "$(brew --prefix)/bin/bash"; echo $?`

Still Returns
```

chsh: /usr/local/bin/bash: non-standard shell
1
```

**Comment by alrra** [comment]
@matthewharwood Can you tell me what the following prints out for your old environment

```bash
cat /etc/shells
```

**Comment by matthewharwood** [comment]
$ cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/bin/bash/bin/bash/usr/local/bin/bash
/bin/bash

**Comment by alrra** [comment]
@matthewharwood Ok, thanks!

You need to remove the `/bin/bash/bin/bash/usr/local/bin/bash` entry from `/etc/shells` (you can use `sudo vim /etc/shells`). After that, run the [`change_default_bash_version.sh`](https://github.com/alrra/dotfiles/blob/efa2d8306158ecb7d3c7cde1641e71053152e6e5/os/os_x/change_default_bash_version.sh) script and things should work.

Note: You can also remove the last `/bin/bash` entry since you already have that included.

**Comment by matthewharwood** [comment]
@alrra you are truly a wizard. Thanks:)

**Comment by alrra** [comment]
> you are truly a wizard. Thanks:)

@matthewharwood Glad it works! Again, I apologize for the inconvenience, the initial issue was a silly mistake on my part.

**Comment by SkydiverFL** [comment]
Interesting... `bash --version` and `$BASH_VERSION` report very different results.

```
Last login: Wed Sep 14 12:30:06 on console
Restored session: Wed Sep 14 12:29:30 EDT 2016
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
-bash: shopt: autocd: invalid shell option name

flackey@Freds-MacBook-Pro: ~
$ bash --version
GNU bash, version 4.3.46(1)-release (x86_64-apple-darwin15.5.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
flackey@Freds-MacBook-Pro: ~
$ echo $BASH_VERSION
3.2.57(1)-release
```
